version = 0.1

[default.deploy.parameters]
confirm_changeset = false
resolve_s3 = true
capabilities = ["CAPABILITY_IAM", "CAPABILITY_NAMED_IAM"]

[default.global.parameters]
stack_name = "hydralert-cloudformation-stack"
region = "us-west-2"
